export const KDM_ECOMMERCE_USER_JWT_TOKEN = "KDM_ECOMMERCE_USER_JWT_TOKEN";
export const KDM_ADMIN_JWT_TOKEN = "KDM_ADMIN_JWT_TOKEN";
export const KDM_BUSSINESS_DEV_JWT_TOKEN = "KDM_BUSSINESS_DEV_JWT_TOKEN";
export const KDM_ANALYST_JWT_TOKEN = "KDM_ANALYST_JWT_TOKEN";

export const LOGGED_IN_USER = "LOGGED_IN_USER";

export const KDM_EMPLOYEE_TOKEN = "KDM_EMPLOYEE_TOKEN";

export const EMPLOYEE_LOCAL_STORAGE_KEY = "loggedInUser";

//CONSTANTS
export const CHEMICAL = "CHEMICAL";
export const PHYSICAL = "PHYSICAL";

export const ONLINE = "ONLINE";
export const OFFLINE = "OFFLINE";
