export const KDM_ECOMMERCE_USER_JWT_TOKEN = "KDM_ECOMMERCE_USER_JWT_TOKEN";
export const KDM_ADMIN_JWT_TOKEN = "KDM_ADMIN_JWT_TOKEN";
export const KDM_BUSSINESS_DEV_JWT_TOKEN = "KDM_BUSSINESS_DEV_JWT_TOKEN";
export const KDM_ANALYST_JWT_TOKEN = "KDM_ANALYST_JWT_TOKEN";
